# Generated by Django 6.0.7 on 2026-08-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('ASC', 'Agent Sourcing et Contracting'), ('ADMINISTRATEUR', 'Administrateur')], max_length=20)),
            ],
        ),
    ]
