# Generated by Django 6.0.7 on 2026-07-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('taux_eur', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
