# Generated by Django 6.0.7 on 2026-07-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0002_fournisseur_remove_article_fabricant_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_nego', models.CharField(max_length=100, unique=True)),
                ('annee', models.IntegerField()),
                ('statut', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negociations', to='users.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='OffreFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=4, max_digits=12)),
                ('devise', models.CharField(max_length=3)),
                ('taux_change_applique', models.DecimalField(decimal_places=6, max_digits=12)),
                ('prix_eur', models.DecimalField(decimal_places=4, max_digits=12)),
                ('moq', models.IntegerField()),
                ('mpq', models.IntegerField()),
                ('lead_time', models.IntegerField()),
                ('ncnr', models.BooleanField(default=False)),
                ('source_prix', models.CharField(blank=True, max_length=100)),
                ('date_validite', models.DateField()),
                ('retenu', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referentiel.fournisseur')),
                ('negociation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='negociations.negociation')),
            ],
        ),
        migrations.CreateModel(
            name='PrixReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PMA', 'PMA'), ('PAV', 'PAV'), ('NEGO', 'NEGO')], max_length=10)),
                ('prix_eur', models.DecimalField(decimal_places=4, max_digits=12)),
                ('annee', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_references', to='referentiel.article')),
            ],
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_vs_pma', models.DecimalField(decimal_places=4, max_digits=12)),
                ('saving_vs_pav', models.DecimalField(decimal_places=4, max_digits=12)),
                ('saving_vs_n1', models.DecimalField(decimal_places=4, max_digits=12)),
                ('gap', models.DecimalField(decimal_places=2, max_digits=6)),
                ('classement', models.IntegerField()),
                ('offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saving', to='negociations.offrefournisseur')),
            ],
        ),
    ]
