# Generated by Django 6.0.7 on 2026-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpn', models.CharField(max_length=100, unique=True)),
                ('mpn', models.CharField(max_length=100)),
                ('fabricant', models.CharField(max_length=200)),
                ('short_desc', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
