# Generated by Django 6.0.7 on 2026-08-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpn', models.CharField(max_length=100, unique=True)),
                ('short_desc', models.CharField(blank=True, max_length=255)),
                ('long_desc', models.TextField(blank=True)),
                ('customer', models.CharField(blank=True, max_length=150)),
                ('site', models.CharField(blank=True, max_length=150)),
                ('famille_achat', models.CharField(blank=True, max_length=150)),
                ('categorie', models.CharField(blank=True, max_length=150)),
                ('obsolete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpnQualifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=100)),
                ('mpn_ref_interne', models.CharField(blank=True, max_length=100)),
                ('pays_origine', models.CharField(blank=True, max_length=100)),
                ('fabricant_nom', models.CharField(max_length=200)),
                ('statut_qualification', models.CharField(max_length=50)),
                ('date_qualification', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpn_qualifies', to='referentiel.article')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('article', 'mpn'), name='uniq_article_mpn')],
            },
        ),
    ]
