# Generated by Django 6.0.7 on 2026-07-29 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('devise', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='fabricant',
        ),
        migrations.RemoveField(
            model_name='article',
            name='mpn',
        ),
        migrations.AddField(
            model_name='article',
            name='customer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='forecast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='long_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='site',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='MpnQualifie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=100)),
                ('fabricant_nom', models.CharField(max_length=200)),
                ('statut_qualification', models.CharField(max_length=50)),
                ('date_qualification', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpn_qualifies', to='referentiel.article')),
            ],
        ),
    ]
