# Generated by Django 6.0.7 on 2026-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Capacitifs', 'Capacitifs'), ('Résistifs', 'Résistifs'), ('Circuit intégré analogique', 'Circuit intégré analogique'), ('Connectique', 'Connectique'), ('Diodes', 'Diodes'), ('Cable et filaire', 'Cable et filaire'), ('Transistors', 'Transistors'), ('Inductifs', 'Inductifs'), ('Electromécanique', 'Electromécanique'), ('Piezo', 'Piezo')], max_length=150),
        ),
        migrations.AlterField(
            model_name='article',
            name='famille_achat',
            field=models.CharField(blank=True, choices=[('Semiconducteur', 'Semiconducteur'), ('Interconnection', 'Interconnection'), ('PCBs', 'PCBs'), ('Passif', 'Passif'), ('Mécanique', 'Mécanique'), ('Electromécanique', 'Electromécanique'), ('Inductifs', 'Inductifs'), ('Power', 'Power'), ('Piezo', 'Piezo'), ('Piles', 'Piles'), ('Carte Mère', 'Carte Mère'), ('Afficheurs', 'Afficheurs'), ('Pièce sur plan', 'Pièce sur plan')], max_length=150),
        ),
    ]
