# Generated by Django 6.0.7 on 2026-08-04 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueNego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('prix_final_eur', models.DecimalField(decimal_places=4, max_digits=12)),
                ('moq_final', models.IntegerField()),
                ('fournisseur_retenu_nom', models.CharField(max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='referentiel.article')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referentiel.fournisseur')),
            ],
        ),
    ]
