import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { getFournisseurs } from '../../../api/referentiel';
import { confirmImportOffres, previewImportOffres } from '../../../api/offres';

export default function OffreImportPage() {
  const nav = useNavigate(); const [file, setFile] = useState(null); const [supplier, setSupplier] = useState(''); const [suppliers, setSuppliers] = useState([]); const [report, setReport] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { getFournisseurs({ actif: true, page_size: 1000 }).then(d => setSuppliers(d.results)); }, []);
  const preview = async (e) => { e.preventDefault(); if (!file) return setError('Choisissez un fichier CSV.'); setError(''); try { setReport(await previewImportOffres(file, supplier)); } catch (err) { setError(err.response?.data?.detail || 'Impossible de lire le fichier.'); } };
  const confirm = async () => { setSaving(true); try { await confirmImportOffres(file, supplier); nav('/offres'); } catch (err) { setError(err.response?.data?.detail || 'Import impossible.'); setSaving(false); } };
  return <div className="max-w-5xl"><Link className="inline-block mb-5 px-3 py-2 rounded border border-slate-200 text-sm" to="/offres">← Retour à la liste des offres</Link><h1 className="text-2xl font-bold text-navy-950">Import des offres fournisseurs</h1><p className="text-sm text-slate-500 mb-6">Importez des offres par article ; aucune négociation n’est requise.</p><form onSubmit={preview} className="bg-white border border-slate-200 rounded-lg p-6"><label className="block text-sm font-medium mb-1">Fournisseur par défaut (facultatif)</label><select className="w-full max-w-md rounded-md border border-slate-300 px-3 py-2 mb-5" value={supplier} onChange={e => setSupplier(e.target.value)}><option value="">— Fournisseur dans le fichier —</option>{suppliers.map(s => <option value={s.id} key={s.id}>{s.nom}</option>)}</select><label className="block border-2 border-dashed border-slate-300 rounded-lg p-8 text-center cursor-pointer"><span className="font-medium">Déposez votre fichier CSV ici ou cliquez pour parcourir</span><input className="hidden" type="file" accept=".csv" onChange={e => setFile(e.target.files[0])}/><span className="block text-xs text-slate-500 mt-2">Colonnes : CPN, Prix unitaire, Devise, MOQ, MPQ, Lead time, Date de validité, NCNR, Source du prix. Ajoutez Fournisseur si aucun fournisseur par défaut n’est choisi.</span>{file && <span className="block text-teal-700 text-sm mt-3">{file.name}</span>}</label>{error && <p className="text-rust-600 text-sm mt-3">{error}</p>}<button className="mt-5 px-4 py-2 rounded-lg bg-navy-950 text-white text-sm font-medium">Prévisualiser l’import →</button></form>{report && <div className="mt-6 bg-white border border-slate-200 rounded-lg overflow-hidden"><div className="p-4 flex justify-between"><span className="text-teal-700 font-medium">✓ {report.nb_ok} ligne(s) prête(s)</span><span className="text-rust-600 font-medium">✕ {report.nb_erreurs} erreur(s)</span></div><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3 text-left">Ligne</th><th className="p-3 text-left">CPN</th><th className="p-3 text-left">Fournisseur</th><th className="p-3 text-left">Prix</th><th className="p-3 text-left">Statut</th></tr></thead><tbody>{report.lignes.map(r => <tr key={r.ligne} className="border-t border-slate-100"><td className="p-3">{r.ligne}</td><td className="p-3 font-mono">{r.cpn}</td><td className="p-3">{r.fournisseur || 'Fournisseur par défaut'}</td><td className="p-3">{r.prix_unitaire}</td><td className={`p-3 ${r.statut === 'OK' ? 'text-teal-700' : 'text-rust-600'}`}>{r.statut === 'OK' ? '✓ Prêt' : `✕ ${r.message}`}</td></tr>)}</tbody></table><div className="p-4 border-t flex justify-end"><button type="button" disabled={saving || report.nb_ok === 0} onClick={confirm} className="px-4 py-2 rounded-lg bg-navy-950 text-white text-sm font-medium disabled:opacity-50">{saving ? 'Import en cours…' : `Valider l’import (${report.nb_ok} ligne(s))`}</button></div></div>}</div>;
}
