import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { getArticles, getFournisseurs } from '../../../api/referentiel';
import { createOffre, getOffre, updateOffre } from '../../../api/offres';

const empty = { article: '', fournisseur: '', prix_unitaire: '', pva: '', devise: 'EUR', moq: 1, mpq: 1, lead_time: 0, ncnr: false, source_prix: '', date_validite: '' };
export default function OffreFormPage() {
 const { id } = useParams(); const edit = Boolean(id); const nav = useNavigate(); const [form,setForm]=useState(empty); const [articles,setArticles]=useState([]); const [suppliers,setSuppliers]=useState([]); const [error,setError]=useState('');
 useEffect(()=>{Promise.all([getArticles({page_size: 1000}),getFournisseurs({actif:true,page_size:1000})]).then(([a,s])=>{setArticles(a.results);setSuppliers(s.results);}); if(edit) getOffre(id).then(setForm);},[id,edit]);
 const change=e=>setForm({...form,[e.target.name]:e.target.type==='checkbox'?e.target.checked:e.target.value});
 const submit=async e=>{e.preventDefault();setError('');try{const payload={...form, article:Number(form.article), fournisseur:Number(form.fournisseur)}; edit?await updateOffre(id,payload):await createOffre(payload);nav('/offres');}catch{setError('Vérifiez les champs obligatoires.');}};
 return <div className="max-w-4xl"><Link className="inline-block mb-5 px-3 py-2 rounded border border-slate-200 text-sm" to="/offres">← Retour à la liste des offres</Link><h1 className="text-2xl font-bold text-navy-950 mb-1">{edit?'Modifier l’offre':'Ajouter une offre'}</h1><p className="text-sm text-slate-500 mb-5">Une offre est liée à un article et un fournisseur, sans négociation.</p><form onSubmit={submit} className="bg-white border border-slate-200 rounded-lg p-6"><div className="grid grid-cols-2 gap-4"><Field label="Article"><select required name="article" value={form.article} onChange={change}><option value="">— Choisir un article —</option>{articles.map(a=><option key={a.id} value={a.id}>{a.cpn} — {a.short_desc}</option>)}</select></Field><Field label="Fournisseur"><select required name="fournisseur" value={form.fournisseur} onChange={change}><option value="">— Choisir un fournisseur —</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.nom}</option>)}</select></Field><Field label="Prix unitaire"><input required type="number" step="0.0001" name="prix_unitaire" value={form.prix_unitaire} onChange={change}/></Field><Field label="PVA (€)"><input required min="0" type="number" step="0.0001" name="pva" value={form.pva} onChange={change}/></Field><Field label="Devise"><select name="devise" value={form.devise} onChange={change}><option>EUR</option><option>USD</option><option>MAD</option></select></Field><Field label="MOQ"><input min="1" type="number" name="moq" value={form.moq} onChange={change}/></Field><Field label="MPQ"><input min="1" type="number" name="mpq" value={form.mpq} onChange={change}/></Field><Field label="Lead time (jours)"><input min="0" type="number" name="lead_time" value={form.lead_time} onChange={change}/></Field><Field label="Date de validité"><input type="date" name="date_validite" value={form.date_validite||''} onChange={change}/></Field><Field label="Source du prix"><input name="source_prix" value={form.source_prix} onChange={change}/></Field><label className="flex items-end gap-2 pb-2 text-sm"><input type="checkbox" name="ncnr" checked={form.ncnr} onChange={change}/> NCNR</label></div>{error&&<p className="text-rust-600 text-sm mt-4">{error}</p>}<div className="mt-6 flex gap-3"><button className="px-4 py-2 rounded-lg bg-navy-950 text-white text-sm font-medium">{edit?'Enregistrer':'Créer l’offre'}</button><Link className="px-4 py-2 rounded-lg border border-slate-300 text-sm" to="/offres">Annuler</Link></div></form></div>;
}
function Field({label,children}){return <label className="text-sm font-medium text-slate-700">{label}<div className="mt-1 [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-slate-300 [&_input]:px-3 [&_input]:py-2 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-slate-300 [&_select]:px-3 [&_select]:py-2">{children}</div></label>}
